# Generated by Django 5.0.14 on 2025-08-29 10:11

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.avatar_upload_to)),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=64, verbose_name='WhatsApp (номер или @)')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='Telegram (@username)')),
                ('vk', models.URLField(blank=True, max_length=255, verbose_name='VK (ссылка)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
