# Generated by Django 5.0.14 on 2025-09-18 17:23

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in ["Склад", "Оператор", "Менеджер", "Директор", "Без роли"]:
        Group.objects.get_or_create(name=name)

def delete_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Склад", "Оператор", "Менеджер", "Директор", "Без роли"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),  # или последняя актуальная миграция
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]

