# Generated by Django 5.0.14 on 2025-09-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_birth_date'),
        ('core', '0003_create_default_groups'),
    ]

    operations = [
    ]
