# Generated by Django 5.0.14 on 2025-09-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250918_2030'),
        ('core', '0005_rename_groups_to_english'),
    ]

    operations = [
    ]
