# Generated by Django 5.0.14 on 2025-09-24 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250918_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='Файл или URL', max_length=200)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('items_upserted', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.TextField()),
                ('name_1c', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('description_ext', models.TextField(blank=True, default='')),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('manufacturer_country', models.CharField(blank=True, default='', max_length=200)),
                ('vendor_code', models.CharField(blank=True, default='', max_length=200)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('pkg_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pkg_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pkg_depth_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.importbatch')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_by', models.CharField(blank=True, default='', max_length=300)),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('active_to', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='importbatch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('contract', 'Contract'), ('infiltration', 'Infiltration'), ('other', 'Other')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.product')),
            ],
            options={
                'unique_together': {('product', 'price_type')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier', 'sku'], name='idx_supplier_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', True), ('barcode__exact', ''), _connector='OR'), fields=('supplier', 'sku'), name='uniq_supplier_sku_when_no_barcode'),
        ),
    ]
