# Generated by Django 5.0.14 on 2025-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('bin__isnull', False)), fields=('warehouse', 'product', 'bin'), name='uniq_inventory_row_not_null_bin'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('bin__isnull', True)), fields=('warehouse', 'product'), name='uniq_inventory_row_null_bin'),
        ),
    ]
