# Generated by Django 5.0.14 on 2025-10-07 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inventory_uniq_inventory_row_not_null_bin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inn', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^\\d{10}(\\d{2})?$')], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН/ОГРНИП')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=1024, verbose_name='Полное наименование')),
                ('registration_country', models.CharField(blank=True, default='РОССИЯ', max_length=128, verbose_name='Страна регистрации')),
                ('address', models.CharField(blank=True, max_length=1024, verbose_name='Адрес')),
                ('meta_json', models.JSONField(blank=True, default=dict, verbose_name='Данные из ЕГРЮЛ (сырые)')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('add_counterparty_by_inn', 'Может добавлять контрагентов по ИНН')],
            },
        ),
        migrations.CreateModel(
            name='CounterpartyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Финансы (сырые)')),
                ('revenue_last', models.BigIntegerField(blank=True, null=True, verbose_name='Выручка (посл. год)')),
                ('profit_last', models.BigIntegerField(blank=True, null=True, verbose_name='Чистая прибыль (посл. год)')),
                ('counterparty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='core.counterparty')),
            ],
        ),
    ]
