# Generated by Django 5.0.14 on 2025-10-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_counterparty_counterpartyfinance'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт компании'),
        ),
        migrations.CreateModel(
            name='CounterpartyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Моб. телефон')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['-created_at'],
            },
        ),
    ]
