# Generated by Django 5.0.14 on 2025-10-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_counterparty_website_counterpartycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpartyfinance',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='counterpartyfinance',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='counterpartyfinance',
            name='profit_last',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Чистая прибыль, последний год'),
        ),
        migrations.AlterField(
            model_name='counterpartyfinance',
            name='revenue_last',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Выручка, последний год'),
        ),
    ]
