# Generated by Django 5.0.14 on 2025-10-07 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_counterpartyfinance_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Выберите одного или нескольких менеджеров.', related_name='managed_counterparties', to=settings.AUTH_USER_MODEL, verbose_name='Закреплённые менеджеры'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
