# Generated by Django 5.0.14 on 2025-10-08 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_counterparty_managers_alter_counterparty_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='actual_address',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Фактический адрес / адрес доставки'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='bank_account',
            field=models.CharField(blank=True, max_length=34, verbose_name='Номер счёта'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=20, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк (наименование)'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.CreateModel(
            name='CounterpartyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название файла/документа')),
                ('file', models.FileField(upload_to='counterparty_docs/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.counterparty')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
