# Generated by Django 5.0.14 on 2025-10-08 10:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_counterparty_actual_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterpartydocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='counterpartydocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='counterpartydocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 8, 10, 18, 23, 944027, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counterpartydocument',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='counterpartydocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
    ]
