# Generated by Django 5.0.14 on 2025-10-14 08:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_counterpartydeletionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyCreateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^\\d{10}(\\d{2})?$')], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН/ОГРНИП')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=1024, verbose_name='Полное наименование')),
                ('registration_country', models.CharField(blank=True, default='РОССИЯ', max_length=128, verbose_name='Страна регистрации')),
                ('address', models.CharField(blank=True, max_length=1024, verbose_name='Адрес')),
                ('actual_address', models.CharField(blank=True, max_length=1024, verbose_name='Фактический адрес / адрес доставки')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк (наименование)')),
                ('bank_bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('bank_account', models.CharField(blank=True, max_length=34, verbose_name='Номер счёта')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='Комментарий ревьюера')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_create_requests', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер-инициатор')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_create_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Кем рассмотрено')),
            ],
            options={
                'verbose_name': 'Заявка на добавление контрагента',
                'verbose_name_plural': 'Заявки на добавление контрагентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='counterpartycreaterequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('inn',), name='uniq_pending_counterparty_create_by_inn'),
        ),
    ]
