# Generated by Django 5.0.14 on 2025-10-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_counterpartycreaterequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyCreateRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='counterparty_request_docs/%Y/%m/%d/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.counterpartycreaterequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Файл заявки на контрагента',
                'verbose_name_plural': 'Файлы заявки на контрагента',
                'ordering': ['-created_at'],
            },
        ),
    ]
