# Generated by Django 5.0.14 on 2025-10-14 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_counterpartycreaterequestdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterpartycreaterequest',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_requests', to='core.counterparty', verbose_name='Созданный контрагент'),
        ),
    ]
