# Generated by Django 5.0.14 on 2025-10-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_counterpartycreaterequest_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterpartycontact',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
    ]
