# Generated by Django 5.0.14 on 2025-10-27 09:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_counterpartycontact_birthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер')),
                ('title', models.CharField(max_length=200, verbose_name='Тема')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('approved', 'Согласована'), ('to_pick', 'В сборку (на склад)'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('done', 'Завершена'), ('rejected', 'Отклонена'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('comment_internal', models.TextField(blank=True, default='', verbose_name='Внутренний комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.counterparty', verbose_name='Контрагент')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('approved', 'Согласована'), ('to_pick', 'В сборку (на склад)'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('done', 'Завершена'), ('rejected', 'Отклонена'), ('canceled', 'Отменена')], default='', max_length=20)),
                ('to_status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('approved', 'Согласована'), ('to_pick', 'В сборку (на склад)'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('done', 'Завершена'), ('rejected', 'Отклонена'), ('canceled', 'Отменена')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кол-во')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Примечание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Товар')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.request')),
            ],
        ),
    ]
