# Generated by Django 5.0.14 on 2025-10-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_request_requestcomment_requesthistory_requestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Кол-во'),
        ),
    ]
