# Generated by Django 5.0.14 on 2025-10-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_requestitem_title_alter_requestitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('approved', 'Согласована'), ('to_pick', 'В сборку (на склад)'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('done', 'Завершена'), ('rejected', 'Отклонена'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('approved', 'Согласована'), ('to_pick', 'В сборку (на склад)'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('done', 'Завершена'), ('rejected', 'Отклонена'), ('canceled', 'Отменена')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('approved', 'Согласована'), ('to_pick', 'В сборку (на склад)'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('done', 'Завершена'), ('rejected', 'Отклонена'), ('canceled', 'Отменена')], max_length=20),
        ),
    ]
