# Generated by Django 5.0.14 on 2025-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_requestquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачена'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('approved', 'Согласована'), ('to_pick', 'Передана на склад'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('delivered', 'Доставлена'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('approved', 'Согласована'), ('to_pick', 'Передана на склад'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('delivered', 'Доставлена'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('approved', 'Согласована'), ('to_pick', 'Передана на склад'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('delivered', 'Доставлена'), ('done', 'Завершена'), ('canceled', 'Отменена')], max_length=20),
        ),
    ]
