# Generated by Django 5.0.14 on 2025-11-05 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_request_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picklists', to='core.request')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PickItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=64)),
                ('unit', models.CharField(default='шт', max_length=16)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.picklist')),
            ],
            options={
                'indexes': [models.Index(fields=['barcode'], name='core_pickit_barcode_e9e400_idx')],
            },
        ),
    ]
