# Generated by Django 5.0.14 on 2025-11-07 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_picklist_pickitem'),
    ]

    operations = [
        # --- чистим старую PickList-связь ---
        migrations.RemoveField(
            model_name='picklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='picklist',
            name='request',
        ),
        migrations.RemoveField(
            model_name='pickitem',
            name='picklist',
        ),

        # --- Meta/индексы/старые поля ---
        migrations.AlterModelOptions(
            name='pickitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='pickitem',
            name='core_pickit_barcode_e9e400_idx',
        ),
        migrations.RemoveField(
            model_name='pickitem',
            name='product_id',
        ),

        # --- поля, которые УЖЕ есть в БД: обновляем только state ---
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='pickitem',
                    name='created_at',
                    field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='pickitem',
                    name='price',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='pickitem',
                    name='updated_at',
                    field=models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),

        # --- новое поле FK: его нужно реально создать в БД ---
        migrations.AddField(
            model_name='pickitem',
            name='request',
            field=models.ForeignKey(
                blank=True,
                null=True,  # временно допускаем null, чтобы миграция прошла
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pick_items',
                to='core.request',
            ),
        ),

        # --- актуализация типов для существующих колонок ---
        migrations.AlterField(
            model_name='pickitem',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pickitem',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pickitem',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pickitem',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=16),
        ),

        # --- удаляем модель PickList ---
        migrations.DeleteModel(
            name='PickList',
        ),
    ]
