# Generated by Django 5.0.14 on 2025-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_picklist_pickitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
    ]
