# Generated by Django 5.0.14 on 2025-11-07 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_picklist_created_by_remove_picklist_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_items', to='core.request'),
        ),
    ]
