# Generated by Django 5.0.14 on 2025-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_pickresult_pickresultitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickitem',
            name='missing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickitem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pickitem',
            name='picked_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
