# Generated by Django 5.0.14 on 2025-12-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_pickitem_missing_pickitem_note_pickitem_picked_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024, verbose_name='Фактический адрес / адрес доставки')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать как основной адрес доставки', verbose_name='Адрес по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-is_default', 'created_at'],
            },
        ),
    ]
