# Generated by Django 5.0.14 on 2025-12-03 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_counterparty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.counterpartyaddress', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.counterpartycontact', verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='request',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
    ]
