# Generated by Django 5.0.14 on 2025-12-03 21:51

import core.models_requests
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_delivery_fields_to_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestquote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Коммерческое предложение', 'verbose_name_plural': 'Коммерческие предложения'},
        ),
        migrations.AddField(
            model_name='requestquote',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Только одно активное КП на заявку', verbose_name='Активное КП'),
        ),
        migrations.AddField(
            model_name='requestquote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('pending_approval', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Не согласована'), ('to_pick', 'Передана на сборку'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('partially_shipped', 'Частично отгружена'), ('shipped', 'Отгружена'), ('delivered', 'Доставлена'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('pending_approval', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Не согласована'), ('to_pick', 'Передана на сборку'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('partially_shipped', 'Частично отгружена'), ('shipped', 'Отгружена'), ('delivered', 'Доставлена'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('pending_approval', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Не согласована'), ('to_pick', 'Передана на сборку'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('partially_shipped', 'Частично отгружена'), ('shipped', 'Отгружена'), ('delivered', 'Доставлена'), ('done', 'Завершена'), ('canceled', 'Отменена')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requestquote',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=core.models_requests._quote_upload_to, verbose_name='Файл КП'),
        ),
        migrations.CreateModel(
            name='RequestQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итого')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product', verbose_name='Товар')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.requestquote')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_items', to='core.requestitem')),
            ],
            options={
                'verbose_name': 'Позиция КП',
                'verbose_name_plural': 'Позиции КП',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RequestShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(blank=True, max_length=32, verbose_name='Номер отгрузки')),
                ('shipped_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отгрузки')),
                ('is_partial', models.BooleanField(default=False, verbose_name='Частичная отгрузка')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий к отгрузке')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.request')),
                ('shipped_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
                'ordering': ['-shipped_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product')),
                ('quote_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.requestquoteitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.requestshipment')),
            ],
            options={
                'verbose_name': 'Позиция отгрузки',
                'verbose_name_plural': 'Позиции отгрузки',
                'ordering': ['id'],
            },
        ),
    ]
