# Generated by Django 5.0.14 on 2025-12-18 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_quote_items_and_shipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('pending_approval', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Не согласована'), ('to_pick', 'Передана на сборку'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('in_delivery', 'В доставке'), ('partially_shipped', 'Частично отгружена'), ('shipped', 'Отгружена'), ('delivered', 'Доставлена'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('pending_approval', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Не согласована'), ('to_pick', 'Передана на сборку'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('in_delivery', 'В доставке'), ('partially_shipped', 'Частично отгружена'), ('shipped', 'Отгружена'), ('delivered', 'Доставлена'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('quote', 'Коммерческое предложение'), ('pending_approval', 'На согласовании'), ('approved', 'Согласована'), ('rejected', 'Не согласована'), ('to_pick', 'Передана на сборку'), ('in_progress', 'Собирается'), ('ready_to_ship', 'Готова к отгрузке'), ('in_delivery', 'В доставке'), ('partially_shipped', 'Частично отгружена'), ('shipped', 'Отгружена'), ('delivered', 'Доставлена'), ('done', 'Завершена'), ('canceled', 'Отменена')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('icon', models.CharField(blank=True, default='📦', max_length=10, verbose_name='Иконка (эмодзи)')),
                ('color', models.CharField(blank=True, default='#667eea', help_text='Цвет для отображения категории', max_length=7, verbose_name='Цвет (hex)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.productcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.productcategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='idx_category_active'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent', 'is_active'], name='core_produc_parent__1eba52_idx'),
        ),
    ]
