# Generated by Django 5.0.14 on 2025-12-24 08:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: ООО "Ваша компания"', max_length=255, verbose_name='Краткое наименование')),
                ('full_name', models.CharField(help_text='Например: Общество с ограниченной ответственностью "Ваша компания"', max_length=500, verbose_name='Полное наименование')),
                ('inn', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^\\d{10,12}$')], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='КПП должен содержать 9 цифр', regex='^\\d{9}$')], verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='ОГРН должен содержать 13 или 15 цифр', regex='^\\d{13,15}$')], verbose_name='ОГРН')),
                ('address', models.TextField(help_text='Например: г. Москва, ул. Примерная, д. 1', verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование банка')),
                ('bank_bik', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='БИК должен содержать 9 цифр', regex='^\\d{9}$')], verbose_name='БИК')),
                ('bank_account', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Расчетный счет должен содержать 20 цифр', regex='^\\d{20}$')], verbose_name='Расчетный счет')),
                ('bank_corr_account', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Корреспондентский счет должен содержать 20 цифр', regex='^\\d{20}$')], verbose_name='Корреспондентский счет')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя')),
                ('director_position', models.CharField(default='Генеральный директор', max_length=255, verbose_name='Должность руководителя')),
                ('accountant_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО главного бухгалтера')),
                ('accountant_position', models.CharField(default='Главный бухгалтер', max_length=255, verbose_name='Должность главного бухгалтера')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные компании не будут отображаться в списках выбора', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Компания, от имени которой оформляется заявка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='Компания (продавец)'),
        ),
    ]
