# Generated by Django 5.0.14 on 2025-12-24 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_company_request_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='bank_corr_account',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Корреспондентский счет должен содержать 20 цифр', regex='^\\d{20}$')], verbose_name='Корреспондентский счет'),
        ),
        migrations.AddField(
            model_name='counterpartycreaterequest',
            name='bank_corr_account',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Корреспондентский счет должен содержать 20 цифр', regex='^\\d{20}$')], verbose_name='Корреспондентский счет'),
        ),
    ]
