# Generated by Django 5.0.14 on 2025-12-24 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_counterparty_bank_corr_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(help_text='Например: г. Москва, ул. Примерная, д. 1', verbose_name='Юридический адрес'),
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('actual', 'Фактический адрес'), ('delivery', 'Адрес доставки'), ('postal', 'Почтовый адрес')], default='actual', max_length=20, verbose_name='Тип адреса')),
                ('address', models.CharField(max_length=1024, verbose_name='Адрес')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать как основной адрес данного типа', verbose_name='Адрес по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Адрес компании',
                'verbose_name_plural': 'Адреса компании',
                'ordering': ['address_type', '-is_default', 'created_at'],
            },
        ),
    ]
